### ISSUE TITLE
pre-commit git hook

### ISSUE THREAD

**Issue by dgahle** [dgahle/PythonRepositoryTemplate#26]
Below is example YAML code for added precommit git hooks.

```
repos:
-   repo: local
    hooks:
    -   id: black
        name: running black
        entry: black
        language: system
        types: [python]
    -   id: flake8
        name: running flake8
        entry: flake8
        language: system
        types: [python]
    -   id: isort
        args: ["--profile", "black"]
        name: running isort
        entry: isort
        language: system
        types: [python]
```

Useful: 
- https://medium.com/@pijpijani/smarter-commits-with-git-pre-commit-hooks-9c7bb3f699bf 
- https://stackoverflow.com/questions/67795922/understanding-how-to-configure-pre-commit-with-repo-local/67796237#67796237
- https://stackoverflow.com/questions/64011304/running-pytest-as-a-pre-commit-hook-no-such-file-or-directory-issue
